import type { Metadata } from 'next';
import { Inter, Montserrat_Alternates } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const montserratAlternates = Montserrat_Alternates({
  subsets: ['latin'],
  display: 'swap',
  weight: '300',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserratAlternates.className}>{children}</body>
    </html>
  );
}
